Repository WildCodeSchool/202209-orleans-php-project-originsdigital, pull requests merged in 2022-12, with the labels that each got.

#1 S01 init
  assets/app.js
  assets/styles/_root.scss
  assets/styles/_wcs.scss
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layoutUser.html.twig
  yarn.lock
Labels: Reviewed

#61 S01US45 Création du footer
  assets/images/logoZeSport.png
  assets/styles/_footer.scss
  assets/styles/app.scss
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/layoutUser.html.twig
Labels: Reviewed, Correction Done

#64 S01US27 Navbar
  assets/images/Ellipse2.png
  assets/styles/_navbar.scss
  assets/styles/_root.scss
  assets/styles/app.scss
  config/packages/doctrine.yaml
  templates/components/_navbar.html.twig
  templates/layoutUser.html.twig
Labels: Reviewed, Correction Done

#71 DEV to MAIN
  assets/app.js
  assets/images/Ellipse2.png
  assets/images/logoZeSport.png
  assets/styles/_footer.scss
  assets/styles/_navbar.scss
  assets/styles/_root.scss
  assets/styles/_wcs.scss
  assets/styles/app.scss
  config/packages/doctrine.yaml
  package.json
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
  templates/layoutUser.html.twig
  yarn.lock
Labels: Reviewed

#72 fix navbar
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#70 S01US47 Création page unitaire vidéo
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/styles/_showVideo.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20221215111540.php
  src/Controller/VideoController.php
  src/DataFixtures/VideoFixtures.php
  src/Entity/Video.php
  src/Repository/VideoRepository.php
  templates/video/index.html.twig
Labels: Reviewed, Conflict Resolved

#79 Fix v2 add link and margin for showvideo
  assets/styles/_showVideo.scss
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/video/index.html.twig
Labels: Reviewed, FIX

#86 S01US52 Création section sponsors
  assets/images/placeHolder.png
  assets/styles/_sponsor.scss
  migrations/Version20221215134652.php
  src/Controller/SponsorController.php
  src/DataFixtures/SponsorFixtures.php
  src/Entity/Sponsor.php
  src/Repository/SponsorRepository.php
  templates/components/_sponsor.html.twig
  templates/layoutUser.html.twig
Labels: Reviewed

#73 S01US31 creation categories
  assets/styles/app.scss
  assets/styles/categories.scss
  config/packages/translation.yaml
  migrations/Version20221215091744.php
  src/Controller/CategoryController.php
  src/DataFixtures/CategoryFixtures.php
  src/Entity/Category.php
  src/Repository/CategoryRepository.php
  templates/base.html.twig
  templates/category/index.html.twig
  templates/components/_navbar.html.twig
  webpack.config.js
Labels: Reviewed

#81 Fix root v1
  assets/images/illusion.png
  assets/styles/_navbar.scss
  assets/styles/_root.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#80 S01US30 Page d'accueil
  assets/styles/_home.scss
  assets/styles/_showVideo.scss
  assets/styles/app.scss
  assets/styles/showVideo.scss
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed, Conflict Resolved

#91 Fix Messenger TABLE
  migrations/Version20221215111540.php
  migrations/Version20221215134652.php
Labels: Reviewed, FIX

#92 Dev to Main
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/illusion.png
  assets/images/placeHolder.png
  assets/styles/_home.scss
  assets/styles/_navbar.scss
  assets/styles/_root.scss
  assets/styles/_sponsor.scss
  assets/styles/app.scss
  assets/styles/categories.scss
  assets/styles/showVideo.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  migrations/Version20221215091744.php
  migrations/Version20221215111540.php
  migrations/Version20221215134652.php
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/SponsorController.php
  src/Controller/VideoController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/SponsorFixtures.php
  src/DataFixtures/VideoFixtures.php
  src/Entity/Category.php
  src/Entity/Sponsor.php
  src/Entity/Video.php
  src/Repository/CategoryRepository.php
  src/Repository/SponsorRepository.php
  src/Repository/VideoRepository.php
  templates/base.html.twig
  templates/category/index.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/_sponsor.html.twig
  templates/home/index.html.twig
  templates/layoutUser.html.twig
  templates/video/index.html.twig
  webpack.config.js
Labels: Reviewed

#93 FIX S02US31 - Création Categories (inclusion edition)
  assets/styles/categories.scss
  templates/category/index.html.twig
Labels: Reviewed, FIX

#94 Fix_Visual_Sponsor_Section
  assets/styles/_sponsor.scss
  assets/styles/app.scss
  composer.lock
  templates/components/_sponsor.html.twig
Labels: Reviewed, FIX

#116 S02 us02 login
  assets/styles/login.scss
  config/packages/security.yaml
  config/routes.yaml
  migrations/Version20221219102136.php
  migrations/Version20221219102731.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: Reviewed
