Repository WildCodeSchool/202209-orleans-php-project-originsdigital, pull requests merged in 2023-01, with the labels that each got.

#117 S02US04 Registration Form
  assets/styles/_flash_messages.scss
  assets/styles/app.scss
  assets/styles/registration.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  symfony.lock
  templates/base.html.twig
  templates/components/_flash_messages.html.twig
  templates/components/_footer.html.twig
  templates/layoutUser.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done

#122 S02US53 ads add on video page
  assets/styles/showVideo.scss
  migrations/Version20221221155445.php
  src/Controller/VideoController.php
  src/DataFixtures/AdFixtures.php
  src/Entity/Advertisement.php
  src/Repository/AdvertRepository.php
  templates/video/index.html.twig
Labels: Reviewed, Correction Done

#128 Fix S02US56
  assets/styles/_navbar.scss
  composer.lock
  src/DataFixtures/VideoFixtures.php
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#130 Fixed the navbar to be responsive in all browsers
  assets/styles/_navbar.scss
Labels: Reviewed, FIX

#132 S02 us03 user profile (edit)
  assets/styles/app.scss
  assets/styles/user_profile.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20230104160350.php
  public/uploads/.gitignore
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/UserType.php
  symfony.lock
  templates/base.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  webpack.config.js
Labels: Conflict Resolved

#136 Fix vue issues
  assets/styles/_flash_messages.scss
  assets/styles/_home.scss
  assets/styles/app.scss
  assets/styles/categories.scss
  assets/styles/login.scss
  assets/styles/registration.scss
  assets/styles/showCategories.scss
  assets/styles/showVideo.scss
  assets/styles/user_profile.scss
  composer.lock
  templates/profile/edit.html.twig
Labels: Reviewed, FIX

#137 DEV to MAIN
  assets/styles/_flash_messages.scss
  assets/styles/_home.scss
  assets/styles/app.scss
  assets/styles/categories.scss
  assets/styles/login.scss
  assets/styles/registration.scss
  assets/styles/showCategories.scss
  assets/styles/showVideo.scss
  assets/styles/user_profile.scss
  composer.lock
  templates/profile/edit.html.twig
Labels: Reviewed

#140 S02 us03b show profile page
  src/Controller/ProfileController.php
  templates/components/_navbar.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: Reviewed, Correction Done

#141 S02US46 admin page
  composer.lock
  config/packages/security.yaml
  src/Controller/AdminController.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/components/_navbar_admin.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed

#143 S02us57 add mention legal
  php.ini
  src/Controller/HomeController.php
  templates/LegalNotices/index.html.twig
  templates/components/_footer.html.twig
Labels: Reviewed

#145 S03US03c - Admin redirection fix
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Conflict Resolved

#151 Fix visuals (login/inscription/profile edit)
  templates/login/index.html.twig
  templates/profile/edit.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#150 FIX placeholder (login/inscription/navbar) + upload on inscription
  src/Form/RegistrationFormType.php
  src/Form/UserType.php
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Conflict Resolved

#159 S03US11 - CRUD videos read
  assets/styles/adminIndex.scss
  assets/styles/app.scss
  src/Controller/AdminVideoController.php
  src/Form/VideoType.php
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/_form.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/new.html.twig
  templates/adminVideo/show.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done

#160 fix avatar and form card V2 login/registration/profil
  assets/styles/registration.scss
  assets/styles/user_profile.scss
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#162 FIX_login_register_pages
  templates/login/index.html.twig
  templates/profile/edit.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#166 S03US37_CRUD_sponsors_read
  assets/styles/_adminIndex.scss
  src/Controller/AdminSponsorController.php
  src/Form/SponsorType.php
  templates/admin_sponsor/_delete_form.html.twig
  templates/admin_sponsor/_form.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/new.html.twig
  templates/admin_sponsor/show.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done

#168 S03US40 CRUD Sponsors ADD
  config/packages/vich_uploader.yaml
  migrations/Version20230110204918.php
  src/Controller/AdminSponsorController.php
  src/Entity/Sponsor.php
  src/Form/SponsorType.php
  templates/admin_sponsor/_form.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/new.html.twig
Labels: Reviewed

#161 S02US9 carrousel
  assets/carrousel.js
  assets/styles/carrousel.scss
  migrations/Version20230109085545.php
  src/Controller/HomeController.php
  src/DataFixtures/VideoFixtures.php
  src/Entity/Video.php
  templates/base.html.twig
  templates/components/_carrousel.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done

#169 S03US38 CRUD sponsors EDIT
  src/Controller/AdminSponsorController.php
  templates/admin_sponsor/_form.html.twig
  templates/admin_sponsor/edit.html.twig
Labels: Reviewed

#174 S03US58 Update sponsors view
  templates/components/_sponsor.html.twig
Labels: Reviewed

#180 Fix CRUD Sponsors
  src/Entity/Sponsor.php
  src/Form/SponsorType.php
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/show.html.twig
Labels: Reviewed

#185 FIX_github_action
  src/Form/SponsorType.php
Labels: Reviewed

#181 S03US29 Video Searchbar
  src/Controller/SearchController.php
  src/Form/VideoSearchType.php
  src/Repository/VideoRepository.php
  templates/components/_navbar.html.twig
  templates/search/index.html.twig
Labels: Reviewed

#191 FIX positionnement dans la page Admin
  templates/admin/index.html.twig
Labels: Reviewed

#195 Fix navbar admin
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, FIX

#196 fix style and visibility of navbar link
  assets/styles/_navbar.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, Conflict Resolved

#193 US33 Create a crud of ads
  assets/styles/_adminIndex.scss
  src/Controller/AdController.php
  src/Form/AdvertisementType.php
  templates/ad/_delete_form.html.twig
  templates/ad/_form.html.twig
  templates/ad/edit.html.twig
  templates/ad/index.html.twig
  templates/ad/new.html.twig
  templates/ad/show.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done

#198 S03US12B CRUD videos - Delete
  src/Form/VideoType.php
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/edit.html.twig
Labels: Reviewed

#197 S03US12 CRUD Videos - Update
  src/Form/VideoType.php
  templates/adminVideo/edit.html.twig
Labels: Reviewed

#199 S03US14A CRUD categories - Read
  src/Controller/AdminCatController.php
  src/Form/CategoryType.php
  templates/adminVideo/show.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/_form.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_cat/new.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done

#201 fix visibility of hover button
  assets/styles/login.scss
  templates/login/index.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, FIX

#202 fix spacing title
  templates/components/_carrousel.html.twig
Labels: Reviewed, FIX

#203 S03 us5 component player video
  assets/images/video1.mp4
  assets/styles/_playerVideo.scss
  assets/styles/app.scss
  templates/base.html.twig
  templates/components/_videoPlayer.html.twig
  templates/video/index.html.twig
Labels: Reviewed

#205 S03 US35 add delete crud ads
  templates/ad/_delete_form.html.twig
Labels: Reviewed

#200 Fix nav admin and fav user
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Conflict Resolved

#207 FIX - Fixed the video upload route - mostly works
  templates/components/_videoPlayer.html.twig
Labels: Reviewed, Correction Done

#208 CRUD Categories - Update
  templates/admin_cat/edit.html.twig
Labels: Reviewed

#209 FIX_searchbar
  templates/components/_navbar_admin.html.twig
  templates/search/index.html.twig
Labels: Reviewed

#210 S03US16 CRUD Categories - Delete
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
Labels: Reviewed

#215 FIX - Is public checkbox in form
  src/Form/VideoType.php
Labels: Reviewed, FIX

#216 FIX remove profil when not log
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#213 FIX - Slug filled automatically in Categories
  src/Controller/AdminCatController.php
Labels: Reviewed, Correction Done

#218 Fix resize ads
  assets/styles/showVideo.scss
Labels: Reviewed, FIX

#212 S03 US5 bloc video component
  assets/images/LOCK.png
  assets/images/video1.mp4
  templates/components/_blocVideo.html.twig
  templates/components/_carrousel.html.twig
Labels: Reviewed

#240 S04US06 Add Favorite Video
  assets/app.js
  migrations/Version20230123092207.php
  package.json
  src/Controller/VideoController.php
  src/Entity/User.php
  src/Entity/Video.php
  templates/video/index.html.twig
  yarn.lock
Labels: Reviewed, Correction Done

#242 Fix videos by category in carrousel
  templates/components/_carrousel.html.twig
Labels: Reviewed, FIX

#243 fix migrations
  migrations/Version20230123092207.php
  migrations/Version20230123152812.php
Labels: Reviewed

#249 US66 algo count views
  src/Controller/VideoController.php
Labels: Reviewed

#244 S04US07 Show favorite videos
  src/Controller/VideoController.php
  templates/components/_navbar.html.twig
  templates/profile/showFavoriteVideo.html.twig
Labels: Reviewed

#248 Fix replace bloc categ show
  assets/styles/_componentVideo.scss
  assets/styles/app.scss
  assets/styles/showCategories.scss
  composer.lock
  package-lock.json
  templates/category/show.html.twig
  yarn.lock
Labels: Reviewed, FIX

#250 Fix hover on show video in category
  assets/styles/_componentVideo.scss
Labels: Reviewed, FIX

#252 Fix ads pics
  assets/styles/showVideo.scss
  src/DataFixtures/AdFixtures.php
  src/DataFixtures/images/amongus.png
  src/DataFixtures/images/horizon.png
  src/DataFixtures/images/ps5.png
  src/DataFixtures/images/rocket.png
  src/DataFixtures/images/warcraft.png
  templates/video/index.html.twig
Labels: Reviewed, Correction Done, FIX

#258 S04US70 Category Upload works - Twig render to come
  config/packages/vich_uploader.yaml
  migrations/Version20230124162949.php
  src/Entity/Category.php
  src/Form/CategoryType.php
Labels: Reviewed

#261 Fix migration remove video_link
  migrations/Version20230123152812.php
Labels: Reviewed, FIX

#262 S04US8 add favicons
  assets/images/icons/apple-touch-icon.png
  assets/images/icons/favicon-16x16.png
  assets/images/icons/favicon-32x32.png
  assets/images/icons/favicon.ico
  templates/base.html.twig
Labels: Reviewed

#268 S04US70 - Index Categories now with background pictures
  assets/styles/categories.scss
  templates/category/index.html.twig
Labels: Reviewed

#269 Fix route to uploads files video and images
  src/DataFixtures/AdFixtures.php
  src/DataFixtures/VideoFixtures.php
  templates/video/index.html.twig
Labels: Reviewed, FIX

#270 Fix add border bottom to title carrousel
  assets/styles/carrousel.scss
  templates/components/_carrousel.html.twig
Labels: Reviewed, FIX

#263 S04 us64 banniere home
  assets/styles/_home.scss
  migrations/Version20230125102235.php
  src/Controller/HomeController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/images/blob.jpg
  src/DataFixtures/images/eldenring.jpg
  src/DataFixtures/images/xbox-game-pass-banniere.jpeg
  src/Entity/Actuality.php
  src/Repository/ActualityRepository.php
  templates/components/_carrouselBanniere.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Correction Done

#264 S04US67 like videos
  migrations/Version20230125153448.php
  src/Controller/VideoController.php
  src/Entity/Video.php
  templates/video/index.html.twig
Labels: Reviewed, Correction Done

#271 Fix view on sponsor's placeholder
  migrations/Version20230125151242.php
  src/DataFixtures/SponsorFixtures.php
  templates/components/_sponsor.html.twig
Labels: Reviewed, Correction Done

#272 Fix add register link to navbar
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#274 FIX - navbar admin to remove Tags
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, FIX

#275 fix searchbar and add card style on result
  composer.lock
  templates/search/index.html.twig
  yarn.lock
Labels: Reviewed

#276 Fix migration
  migrations/Version20230125102235.php
Labels: Reviewed

#277 Fix Refonte design new navbar to admin
  assets/styles/_navbarAdmin.scss
  assets/styles/app.scss
  templates/components/_navbar_admin.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed, FIX

#283 S04US65 Count Likes
  templates/video/index.html.twig
Labels: Reviewed

#284 Fix route uploads with subfolder
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/AdFixtures.php
  src/DataFixtures/images/actualities/blob.jpg
  src/DataFixtures/images/actualities/eldenring.jpg
  src/DataFixtures/images/actualities/xbox-game-pass-banniere.jpeg
  src/DataFixtures/images/ads/amongus.png
  src/DataFixtures/images/ads/horizon.png
  src/DataFixtures/images/ads/ps5.png
  src/DataFixtures/images/ads/rocket.png
  src/DataFixtures/images/ads/warcraft.png
  templates/components/_carrouselBanniere.html.twig
  templates/video/index.html.twig
Labels: Reviewed, FIX

#285 Fix refonte admin page
  assets/styles/_adminIndex.scss
  assets/styles/_flash_messages.scss
  templates/admin/index.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
Labels: Reviewed, FIX

#291 FIX fill in like button
  templates/video/index.html.twig
Labels: Reviewed, FIX

#289 S04US73 add crud index of actuality
  src/Controller/ActualityController.php
  src/Form/ActualityType.php
  templates/actuality/_delete_form.html.twig
  templates/actuality/_form.html.twig
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/actuality/new.html.twig
  templates/actuality/show.html.twig
  templates/components/_navbar_admin.html.twig
Labels: Reviewed

#292 FIX design of btn and show video
  assets/styles/showVideo.scss
  templates/video/index.html.twig
Labels: Reviewed, Conflict Resolved

#290 S04US72 Error Pages
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed, Correction Done

#293 FIX - Links navbar & footer
  assets/styles/_footer.scss
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#294 Fix re-marge all page without flash container
  assets/styles/_favorites.scss
  assets/styles/_home.scss
  assets/styles/app.scss
  assets/styles/categories.scss
  assets/styles/registration.scss
  assets/styles/showCategories.scss
  templates/actuality/index.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/profile/showFavoriteVideo.html.twig
Labels: Reviewed, FIX

#297 FIX placeholder if no user photo
  assets/styles/user_profile.scss
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/profile/edit.html.twig
Labels: Reviewed, FIX

#298 FIXed top margin on videos
  assets/styles/showVideo.scss
Labels: Reviewed, FIX

#299 fix profil
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: Reviewed, FIX

#300 Fix - Admin Video
  migrations/Version20221215111540.php
  src/Entity/Video.php
  src/Form/VideoType.php
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/_form.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
Labels: Reviewed, FIX

#310 Fix btn search nav
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#311 FIX design refonte ALL INDEX admin
  templates/actuality/index.html.twig
  templates/ad/_delete_form.html.twig
  templates/ad/index.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
Labels: Reviewed, FIX

#304 S04US74 make crud with add banniere
  assets/styles/_adminIndex.scss
  config/packages/vich_uploader.yaml
  src/Controller/ActualityController.php
  src/Entity/Actuality.php
  src/Form/ActualityType.php
  templates/actuality/_form.html.twig
  templates/actuality/new.html.twig
Labels: Reviewed

#302 Dev To Main
  assets/styles/_adminIndex.scss
  assets/styles/_favorites.scss
  assets/styles/_flash_messages.scss
  assets/styles/_footer.scss
  assets/styles/_home.scss
  assets/styles/_navbarAdmin.scss
  assets/styles/app.scss
  assets/styles/categories.scss
  assets/styles/registration.scss
  assets/styles/showCategories.scss
  assets/styles/showVideo.scss
  assets/styles/user_profile.scss
  config/packages/vich_uploader.yaml
  migrations/Version20221215111540.php
  migrations/Version20230125102235.php
  src/Controller/ActualityController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/AdFixtures.php
  src/DataFixtures/images/actualities/blob.jpg
  src/DataFixtures/images/actualities/eldenring.jpg
  src/DataFixtures/images/actualities/xbox-game-pass-banniere.jpeg
  src/DataFixtures/images/ads/amongus.png
  src/DataFixtures/images/ads/horizon.png
  src/DataFixtures/images/ads/ps5.png
  src/DataFixtures/images/ads/rocket.png
  src/DataFixtures/images/ads/warcraft.png
  src/Entity/Actuality.php
  src/Entity/Video.php
  src/Form/ActualityType.php
  src/Form/VideoType.php
  templates/actuality/_delete_form.html.twig
  templates/actuality/_form.html.twig
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/actuality/new.html.twig
  templates/actuality/show.html.twig
  templates/admin/index.html.twig
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/_form.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/components/_carrouselBanniere.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/layoutAdmin.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/profile/showFavoriteVideo.html.twig
  templates/video/index.html.twig
Labels: Reviewed

#309 S04US76 crud banniere - delete
  templates/actuality/_delete_form.html.twig
  templates/actuality/index.html.twig
Labels: Reviewed

#313 FIX sponsor route (security fail)
  src/Controller/SponsorController.php
Labels: Reviewed, FIX

#314 FIX rework index admin
  templates/actuality/index.html.twig
  templates/ad/_delete_form.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
Labels: Reviewed, FIX

#315 FIX replace with navbar admin
  assets/styles/_adminIndex.scss
Labels: Reviewed, FIX

#319 fix space on searchbar
  templates/search/index.html.twig
Labels: Reviewed, FIX

#320 Fix hover to li admin nav
  assets/styles/_navbarAdmin.scss
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, FIX

#317 FIX - Categories backgrounds in fixtures
  config/packages/vich_uploader.yaml
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/VideoFixtures.php
  src/DataFixtures/images/backgrounds/League-of-Legends.jpg
  src/DataFixtures/images/backgrounds/overwatch-2.webp
  src/DataFixtures/images/backgrounds/rocket-league.webp
  src/DataFixtures/images/backgrounds/world-warcraft.webp
  templates/category/index.html.twig
Labels: Reviewed, Correction Done

#321 Fix search result
  assets/styles/_home.scss
  templates/search/index.html.twig
Labels: Reviewed, FIX

#323 DEV to MAIN
  assets/styles/_adminIndex.scss
  assets/styles/_home.scss
  assets/styles/_navbarAdmin.scss
  assets/styles/showVideo.scss
  config/packages/vich_uploader.yaml
  src/Controller/SponsorController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/VideoFixtures.php
  src/DataFixtures/images/backgrounds/League-of-Legends.jpg
  src/DataFixtures/images/backgrounds/overwatch-2.webp
  src/DataFixtures/images/backgrounds/rocket-league.webp
  src/DataFixtures/images/backgrounds/world-warcraft.webp
  templates/actuality/_delete_form.html.twig
  templates/actuality/index.html.twig
  templates/ad/_delete_form.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
  templates/category/index.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar_admin.html.twig
  templates/search/index.html.twig
Labels: Reviewed

#316 add slider for carousel on mobile
  assets/carrousel.js
  package.json
  templates/components/_carrousel.html.twig
  yarn.lock
Labels: Reviewed, Correction Done

#324 Fix margin-top
  assets/styles/showVideo.scss
Labels: Reviewed, FIX

#327 S04US75 crud edit banniere
  templates/actuality/edit.html.twig
Labels: Reviewed

#325 FIX avatar on admin sidebar
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, FIX

#326 Fix contain for media admin
  assets/styles/_adminIndex.scss
  templates/actuality/index.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/index.html.twig
Labels: Reviewed, FIX

#342 FIX view sponsor's admin
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/show.html.twig
Labels: Reviewed, FIX

#343 Fix count like in btn and not login condition btn
  assets/styles/showVideo.scss
  templates/video/index.html.twig
Labels: Reviewed, FIX

#349 Fix place search link to nav
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#352 Fix category view empty
  assets/styles/showCategories.scss
  templates/category/show.html.twig
Labels: Reviewed, FIX

#353 Fix position flash message
  assets/styles/_flash_messages.scss
Labels: Reviewed, FIX

#346 S05US77 crud show banniere
  assets/styles/_adminIndex.scss
  templates/actuality/show.html.twig
Labels: Reviewed, Conflict Resolved, FIX

#348 Fix preview premium on carrousel and hover lock to login
  assets/styles/carrousel.scss
  templates/components/_blocVideo.html.twig
  templates/components/_thumbnailPremium.html.twig
Labels: Reviewed, Correction Done, FIX

#355 FIX - Buttons colors + right buttons at the right places
  assets/styles/_root.scss
  templates/admin_cat/_form.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
Labels: Reviewed, FIX

#361 Fix vich uploader
  config/packages/vich_uploader.yaml
Labels: Reviewed, FIX

#365 FIX size of inputs
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, FIX

#366 S05US79 - Upload for ads
  config/packages/vich_uploader.yaml
  migrations/Version20230130110400.php
  src/Entity/Advertisement.php
  src/Form/AdvertisementType.php
Labels: Reviewed

#364 Fix doublon navbar admin
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done, FIX

#369 S05US78 upload banniere
  assets/styles/_adminIndex.scss
  migrations/Version20230130112037.php
  src/Entity/Actuality.php
  src/Form/ActualityType.php
  templates/actuality/index.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/show.html.twig
Labels: Reviewed

#371 Fix replace color in root with theme color
  assets/styles/_root.scss
  templates/components/_sponsor.html.twig
Labels: Reviewed, FIX

#373 FIX - Buttons admin Categories
  templates/admin_cat/_form.html.twig
  templates/admin_cat/edit.html.twig
Labels: Reviewed, FIX

#372 Dev To Main
  assets/carrousel.js
  assets/styles/_adminIndex.scss
  assets/styles/_flash_messages.scss
  assets/styles/_root.scss
  assets/styles/carrousel.scss
  assets/styles/showCategories.scss
  assets/styles/showVideo.scss
  config/packages/vich_uploader.yaml
  migrations/Version20230130110400.php
  migrations/Version20230130112037.php
  package.json
  src/Entity/Actuality.php
  src/Entity/Advertisement.php
  src/Form/ActualityType.php
  src/Form/AdvertisementType.php
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/_form.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/show.html.twig
  templates/category/show.html.twig
  templates/components/_blocVideo.html.twig
  templates/components/_carrousel.html.twig
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/components/_sponsor.html.twig
  templates/components/_thumbnailPremium.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/video/index.html.twig
  yarn.lock
Labels: Reviewed

#375 Fix readme remake
  README.md
Labels: Reviewed, FIX

#367 FIX - Buttons in Admin Video
  templates/adminVideo/_form.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
Labels: Reviewed, Correction Done, FIX

#368 FIX - Boutons Admin Ads
  src/Controller/AdController.php
  src/Controller/AdminCatController.php
  templates/ad/_form.html.twig
  templates/ad/edit.html.twig
  templates/ad/index.html.twig
  templates/ad/new.html.twig
  templates/ad/show.html.twig
  templates/admin_cat/index.html.twig
Labels: Reviewed, FIX

#406 FIX size profile placeholder
  assets/styles/user_profile.scss
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: Reviewed, FIX

#370 FIX - Buttons for Admin Actualities
  src/Controller/ActualityController.php
  templates/actuality/_form.html.twig
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/actuality/new.html.twig
  templates/actuality/show.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_cat/new.html.twig
Labels: Reviewed, FIX

#403 FIX link favorite if not connected
  templates/components/_footer.html.twig
Labels: Reviewed, FIX

#408 Fix - Boutons Admin Sponsors
  src/Controller/AdminSponsorController.php
  templates/admin_sponsor/_form.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/new.html.twig
  templates/admin_sponsor/show.html.twig
Labels: Reviewed, Conflict Resolved

#409 FIX vich image class modif
  templates/admin_cat/index.html.twig
Labels: Reviewed, FIX

#411 FIX - Form helpers added
  src/Form/CategoryType.php
  src/Form/VideoType.php
Labels: Reviewed, FIX

#410 Fixed the size of pictures in edit categories + others in SCSS
  assets/styles/_adminIndex.scss
  templates/admin_cat/edit.html.twig
Labels: Reviewed, FIX

#412 Fix carrousel empty
  assets/styles/carrousel.scss
  templates/components/_carrousel.html.twig
Labels: Reviewed, FIX

#405 FIX grammar
  templates/admin/index.html.twig
  templates/adminVideo/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/show.html.twig
Labels: Reviewed, Conflict Resolved, FIX

#414 FIX - Show & Index Video
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
  templates/admin_sponsor/edit.html.twig
Labels: Reviewed, FIX

#415 Dev To Main
  README.md
  assets/styles/_adminIndex.scss
  assets/styles/carrousel.scss
  assets/styles/user_profile.scss
  src/Controller/ActualityController.php
  src/Controller/AdController.php
  src/Controller/AdminCatController.php
  src/Controller/AdminSponsorController.php
  src/Form/CategoryType.php
  src/Form/VideoType.php
  templates/actuality/_form.html.twig
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/actuality/new.html.twig
  templates/actuality/show.html.twig
  templates/ad/_form.html.twig
  templates/ad/edit.html.twig
  templates/ad/index.html.twig
  templates/ad/new.html.twig
  templates/ad/show.html.twig
  templates/admin/index.html.twig
  templates/adminVideo/_form.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_cat/new.html.twig
  templates/admin_sponsor/_form.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
  templates/admin_sponsor/new.html.twig
  templates/admin_sponsor/show.html.twig
  templates/components/_carrousel.html.twig
  templates/components/_footer.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: Reviewed
