Repository WildCodeSchool/202209-orleans-php-project-originsdigital, pull requests merged in 2023-02, with the labels that each got.

#417 FIX repeated button category admin
  templates/admin_cat/index.html.twig
Labels: Reviewed, FIX

#416 FIX restyle legal notice
  assets/styles/_home.scss
  templates/LegalNotices/index.html.twig
Labels: Reviewed, Correction Done, FIX

#413 FIX sponsors size and added filter
  assets/styles/_sponsor.scss
  templates/components/_sponsor.html.twig
Labels: Reviewed, Correction Done, FIX

#418 FIX sponsors size admin
  templates/admin_sponsor/index.html.twig
Labels: Reviewed, FIX

#419 FIX - Login message
  assets/styles/_flash_messages.scss
  templates/login/index.html.twig
Labels: Reviewed, FIX

#424 nl2br
  templates/video/index.html.twig
Labels: Reviewed, FIX

#423 Removed the Show part in Video & Categories
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
  templates/admin_cat/index.html.twig
Labels: Reviewed, FIX

#422 Ad Link + Ad delete
  src/Controller/AdController.php
  src/Entity/Advertisement.php
Labels: Reviewed, FIX

#421 FIX order videos by name on admin side
  src/Controller/AdminVideoController.php
Labels: Reviewed, FIX

#431 FIX - Show updated at in video descrption
  templates/video/index.html.twig
Labels: Reviewed, FIX

#432 Buttons outline
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/ad/edit.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
Labels: Reviewed, FIX

#441 Admin Premium
  templates/adminVideo/index.html.twig
Labels: Reviewed, FIX

#443 Dev To Main
  assets/styles/_flash_messages.scss
  assets/styles/_home.scss
  assets/styles/_sponsor.scss
  src/Controller/AdController.php
  src/Controller/AdminVideoController.php
  src/Entity/Advertisement.php
  templates/LegalNotices/index.html.twig
  templates/actuality/edit.html.twig
  templates/actuality/index.html.twig
  templates/ad/edit.html.twig
  templates/ad/index.html.twig
  templates/adminVideo/edit.html.twig
  templates/adminVideo/index.html.twig
  templates/adminVideo/show.html.twig
  templates/admin_cat/edit.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/edit.html.twig
  templates/admin_sponsor/index.html.twig
  templates/components/_sponsor.html.twig
  templates/login/index.html.twig
  templates/video/index.html.twig
Labels: Reviewed

#442 Fix - Delete buttons
  templates/actuality/_delete_form.html.twig
  templates/ad/_delete_form.html.twig
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/_delete_form.html.twig
Labels: Reviewed, FIX

#444 fix resize bloc thumbnail
  assets/styles/carrousel.scss
  templates/components/_carrousel.html.twig
  templates/components/_thumbnail.html.twig
  templates/video/index.html.twig
Labels: Reviewed, FIX

#447 Fix add margin top for empty condition of banniere
  assets/styles/_home.scss
Labels: Reviewed, FIX

#457 Fix view show cat
  assets/styles/_componentVideo.scss
  assets/styles/_favorites.scss
  assets/styles/carrousel.scss
  templates/base.html.twig
  templates/category/show.html.twig
  templates/components/_blocVideo.html.twig
  templates/profile/showFavoriteVideo.html.twig
  templates/search/index.html.twig
Labels: Reviewed, FIX

#451 Fix resize and condition when empty
  assets/styles/showVideo.scss
  src/Controller/VideoController.php
  templates/video/index.html.twig
Labels: Reviewed, Correction Done, FIX

#459 Mixed premium and public - now fixed
  templates/adminVideo/index.html.twig
Labels: Reviewed, FIX

#458 Fix flash message component
  assets/styles/_flash_messages.scss
  src/Controller/ActualityController.php
  src/Controller/AdController.php
  src/Controller/AdminCatController.php
  src/Controller/AdminSponsorController.php
  src/Controller/AdminVideoController.php
  templates/components/_flash_messages.html.twig
Labels: Reviewed, Correction Done, FIX

#460 Dev to Main
  assets/styles/_componentVideo.scss
  assets/styles/_favorites.scss
  assets/styles/_flash_messages.scss
  assets/styles/_home.scss
  assets/styles/carrousel.scss
  assets/styles/showVideo.scss
  src/Controller/ActualityController.php
  src/Controller/AdController.php
  src/Controller/AdminCatController.php
  src/Controller/AdminSponsorController.php
  src/Controller/AdminVideoController.php
  src/Controller/VideoController.php
  templates/actuality/_delete_form.html.twig
  templates/ad/_delete_form.html.twig
  templates/adminVideo/_delete_form.html.twig
  templates/adminVideo/index.html.twig
  templates/admin_cat/_delete_form.html.twig
  templates/admin_cat/index.html.twig
  templates/admin_sponsor/_delete_form.html.twig
  templates/base.html.twig
  templates/category/show.html.twig
  templates/components/_blocVideo.html.twig
  templates/components/_carrousel.html.twig
  templates/components/_flash_messages.html.twig
  templates/components/_thumbnail.html.twig
  templates/profile/showFavoriteVideo.html.twig
  templates/search/index.html.twig
  templates/video/index.html.twig
Labels: Reviewed

#462 Fix hover to sponsor
  assets/styles/_sponsor.scss
Labels: Reviewed, FIX

#464 Fix - W3C
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
Labels: Reviewed, FIX

#466 Fix add title on blocVideo
  assets/styles/_adminIndex.scss
  assets/styles/_componentVideo.scss
  assets/styles/_favorites.scss
  templates/category/show.html.twig
  templates/components/_thumbnail.html.twig
  templates/profile/showFavoriteVideo.html.twig
Labels: Reviewed, FIX

#467 Fix center text
  templates/category/show.html.twig
  templates/profile/showFavoriteVideo.html.twig
Labels: Reviewed, FIX

#463 fix avatar size
  templates/components/_navbar_admin.html.twig
Labels: Reviewed, Correction Done, FIX

#468 FIX - Categories Fixtures
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/images/backgrounds/hearthstone.jpg
  src/DataFixtures/images/backgrounds/mario-kart.webp
Labels: Reviewed, FIX

#470 Positive duration
  src/Entity/Video.php
Labels: Reviewed, FIX

#469 Fix add fixtures to actu and sponsor
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/SponsorFixtures.php
  src/DataFixtures/images/actualities/blob.jpg
  src/DataFixtures/images/actualities/eldenring.jpg
  src/DataFixtures/images/actualities/world-lol.jpg
  src/DataFixtures/images/actualities/world-over.jpg
  src/DataFixtures/images/actualities/world-rl.jpg
  src/DataFixtures/images/actualities/world-wow.webp
  src/DataFixtures/images/actualities/xbox-game-pass-banniere.jpeg
  src/DataFixtures/images/logos/Atos_logo.png
  src/DataFixtures/images/logos/Coca-Cola_logo.png
  src/DataFixtures/images/logos/IBM_logo.png
  src/DataFixtures/images/logos/amazon.png
Labels: Reviewed, FIX

#471 Fix add place like cat and fav
  assets/styles/_componentVideo.scss
  templates/search/index.html.twig
Labels: Reviewed, FIX

#472 Dev To Main
  assets/styles/_adminIndex.scss
  assets/styles/_componentVideo.scss
  assets/styles/_favorites.scss
  assets/styles/_sponsor.scss
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/SponsorFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/images/actualities/blob.jpg
  src/DataFixtures/images/actualities/eldenring.jpg
  src/DataFixtures/images/actualities/world-lol.jpg
  src/DataFixtures/images/actualities/world-over.jpg
  src/DataFixtures/images/actualities/world-rl.jpg
  src/DataFixtures/images/actualities/world-wow.webp
  src/DataFixtures/images/actualities/xbox-game-pass-banniere.jpeg
  src/DataFixtures/images/backgrounds/hearthstone.jpg
  src/DataFixtures/images/backgrounds/mario-kart.webp
  src/DataFixtures/images/logos/Atos_logo.png
  src/DataFixtures/images/logos/Coca-Cola_logo.png
  src/DataFixtures/images/logos/IBM_logo.png
  src/DataFixtures/images/logos/amazon.png
  src/Entity/Video.php
  templates/base.html.twig
  templates/category/show.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/components/_thumbnail.html.twig
  templates/profile/showFavoriteVideo.html.twig
  templates/search/index.html.twig
Labels: Reviewed

#473 Fix bloc size
  assets/styles/_componentVideo.scss
Labels: Reviewed, FIX

#474 Dev to Main DEF
  assets/styles/_componentVideo.scss
Labels: Reviewed
